import Head from "next/head";

export default function DataGovernanceProcesses() {
  return (
    <>
      <main className=" min-h-screen  py-24 top-0 px-26  md:pt-18 bg-main-color-gradient flex flex-col items-center">
        <Head>
          <title>Data Governance Toolkit</title>
          <meta
            name="The Data Governance Toolkit is an online platform
          that helps community based z better manage and coordinate
          all of their data activities and data management in one place"
            content="Generated by create next app"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className="container px-5 md:px-8">
          <article className="">
            <h2 className="mt-14 mb-5 tracking-wide md:self-start"></h2>
            <p></p>
            <div></div>
          </article>
        </section>
      </main>
    </>
  );
}
