import Head from "next/head";
import Image from "next/image";
import heroIcons from "../public/home-img/hero-icons.svg";
import icon01Section01 from "../public/home-img/icon-01-section-01.svg";
import icon02Section01 from "../public/home-img/icon-02-section-01.svg";
import icon03Section01 from "../public/home-img/icon-03-section-01.svg";
import icon04Section01 from "../public/home-img/icon-04-section-01.svg";
import icon05Section01 from "../public/home-img/icon-05-section-01.svg";
import iconCommunityOrg from "../public/home-img/icon-community-organisation.svg";
import iconPlatformableProcesses from "../public/home-img/icon-platformable-processes.svg";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <Layout>
      <main className="min-h-screen  top-0">
        <Head>
          <title>Data Governance Toolkit</title>
          <meta
            name="The Data Governance Toolkit is an online platform
          that helps community based organizations better manage and coordinate
          all of their data activities and data management in one place"
            content="Generated by create next app"
          />
          <link rel="icon" href="/platformable-icon-logo.svg" />
        </Head>
        <div className="bg-image-section">
          <section className=" container flex flex-col px-8 pt-28 sm:h-screen md:grid  md:pt-18  grid-cols-2 grid-rows-7 gap-9 sm:gap-2">
            <h1 className="col-start-2  row-start-2 self-center">
              Data that works for you
            </h1>
            <h2 className="col-start-2 sm:w-4/5 row-start-3 self-start">
              Data systems for community health and non-profit-organizations
            </h2>
            <div className="col-start-2 row-start-4 self-start">
              <Image
                src={heroIcons}
                width={700}
                height={150}
                alt="hero-icons"
              ></Image>
            </div>

            <p className="col-start-2 row-start-5">
              The <strong>Data Governance Toolkit</strong> is an online platform
              that helps community based organizations better manage and
              coordinate all of their data activities and data management in one
              place
            </p>
            <div className="col-start-2 row-start-6 md:place-self-start md:justify-self-center md:w-full flex ">
              <button className="w-5/12 rounded-md sm:min-h-10 bg-blue-900 px-3 py-1 mr-6 text-white font-semibold tracking-wide">
                Demo our product
              </button>
              <button className="w-5/12 rounded-md sm:min-h-10 bg-yellow-500 px-3 py-1  font-semibold tracking-wide ">
                Contact us
              </button>
            </div>
          </section>
        </div>

        <section className="flex flex-col py-9 items-center ">
          <h2 className="w-9/12  text-left">
            Data collected through your activities has the power to transform
            your organisation and lead to:
          </h2>
          {/* justify-around items-center */}
          <ul className="w-9/12 flex flex-col md:grid md:grid-cols-2  lg:grid-cols-5 lg:w-11/12 md:gap-7 font-bold p-4">
            <li className=" h-64  shadow-xl rounded-lg p-4 my-6 block text-center  lg:h-72">
              <figure className="mt-5">
                <Image
                  src={icon01Section01}
                  width={100}
                  height={100}
                  alt="service delivery"
                ></Image>

                <figcaption className="mt-5">
                  More effective service delivery
                </figcaption>
              </figure>
            </li>
            <li className=" h-64 shadow-xl rounded-lg p-4 my-6 block text-center lg:h-72">
              <figure className="mt-5">
                <Image
                  src={icon02Section01}
                  width={100}
                  height={100}
                  alt="easier reporting"
                ></Image>
                <figcaption className="mt-5">
                  Easier reporting to boards and funders
                </figcaption>
              </figure>
            </li>
            <li className=" h-64 shadow-xl rounded-lg p-4 my-6 block text-center lg:h-72">
              <figure className="mt-5">
                <Image
                  src={icon03Section01}
                  width={100}
                  height={100}
                  alt="share with community"
                ></Image>
                <figcaption className="mt-5">
                  Demonstrated impact to share with your community
                </figcaption>
              </figure>
            </li>
            <li className="h-64 shadow-xl rounded-lg p-4 my-6 block text-center lg:h-72 ">
              <figure className="mt-5">
                <Image
                  src={icon04Section01}
                  width={100}
                  height={100}
                  alt="evidence-based investmenst and program decisions"
                ></Image>
                <figcaption className="mt-5">
                  Making evidence-based investments and program decisions
                </figcaption>
              </figure>
            </li>
            <li className=" h-64 shadow-xl rounded-lg p-4 my-6 block text-center lg:h-72">
              <figure className="mt-5">
                <Image
                  src={icon05Section01}
                  width={100}
                  height={100}
                  alt="transparency and accountability"
                ></Image>
                <figcaption className="mt-5">
                  Better participation through transparency and accountability
                </figcaption>
              </figure>
            </li>
          </ul>
        </section>
        <section className="min-vh-150 px-3 md:px-28 flex flex-col justify-around text-center bg-main-color-gradient">
          <h2 className=" font-semibold py-4 md:mb-7 tracking-wide mt-10 md:h-1/5">
            The <strong>Data Governance Toolkit</strong> platform helps you
            ensure that you have the policies, processes and datasets collected
            in one place to help you manage your data
          </h2>
          <ul className="flex flex-col text-left  text-2xl mt-10 md:mt-0 md:text-lg md:grid md:grid-cols-2 xl:w-full xl:flex xl:flex-row md:h-2/5 justify-between">
            <li className="font-semibold  px-6 flex">
              <p className="mr-4">&#10004;</p> Practical
            </li>
            <li className="font-semibold  px-6 flex">
              <p className="mr-4">&#10004;</p> Ethical
            </li>
            <li className="font-semibold  px-6 flex">
              <p className="mr-4">&#10004;</p>
              Privacy-focused
            </li>
            <li className="font-semibold  px-6 flex">
              <p className="mr-4">&#10004;</p>
              Regulatory compilant
            </li>

            <li className="font-semibold  px-6 flex">
              <p className="mr-4">&#10004;</p> Responsible
            </li>
            <li className="font-semibold  px-6 flex">
              <p className="mr-4">&#10004;</p> Equitable
            </li>
            <li className="font-semibold  px-6 flex">
              <p className="mr-4">&#10004;</p> Secure
            </li>
          </ul>

          <div className="grid grid-rows-2 md:grid-cols-2 gap-5 py-2 md:gap-6 md:pb-7 self-center justify-items-center  md:h-2/5 md:justify-evenly ">
            <h3 className="text-3xl font-bold  self-center md:col-span-full">
              Learn more
            </h3>

            <div className="w-48 bg-main-color rounded-lg border-solid border-2 border-yellow-400 p-5 md:row-start-2">
              <Image
                src={iconCommunityOrg}
                width={130}
                height={150}
                alt="evidence-based investmenst and program decisions"
              ></Image>
            </div>
            <div className="w-48 bg-main-color rounded-lg border-solid border-2 border-yellow-400 p-5 md:row-start-2">
              <Image
                src={iconPlatformableProcesses}
                width={200}
                height={220}
                alt="evidence-based investmenst and program decisions"
              ></Image>
            </div>
          </div>
        </section>
      </main>
    </Layout>
  );
}
